apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshveggies-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx

  rules:
    - http:
        # MAIN PAGE
        - path: /
          pathType: Prefix
          backend:
            service:
              name: main-service
              port:
                number: 80

        # HOME
        - path: /home(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: home-service
              port:
                number: 80

        # CART
        - path: /cart(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: cart-service
              port:
                number: 80

        # CHECKOUT
        - path: /checkout(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: checkout-service
              port:
                number: 80

        # LOGIN
        - path: /login(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: login-service
              port:
                number: 80

        # SIGNUP
        - path: /signup(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: signup-service
              port:
                number: 80